### ISSUE TITLE
Can't connect to lan

### ISSUE THREAD

**Issue by airaizor** [AllTheMods/ATM-Illumination#10]
I'm trying to play this mod pack in a lan setting but we can't connect we get a java error every time. we play on other modpack without problems

**Comment by al132** [comment]
Could you be more specific about what the error says please?

**Comment by airaizor** [comment]
Internal exception java.io.ioexception:an existion connection was forcibly closed by the remote host

**Comment by SargeTV** [comment]
Getting the same error when trying to connect to lan

**Comment by teagan75** [comment]
Same issue. This is the part of the log where it is tagged fatal.
https://pastebin.com/9LNvy3jj

**Comment by aliatic** [comment]
Same issue - Internal exception java.io etc as listed above.

**Comment by al132** [comment]
I've heard that this issue is now fixed as of the most recent update
