### ISSUE TITLE
Game crash, first night being shot by a skeleton.

### ISSUE THREAD

**Issue by Techatar** [AllTheMods/ATM-Illumination#11]
[crash-2017-03-05_17.31.02-server.txt](https://github.com/AllTheMods/ATM-Illumination/files/819567/crash-2017-03-05_17.31.02-server.txt)

Single player game 
Completely vanilla (no modifications to mod pack, no resource packs etc)
10GB allocated

**Comment by Techatar** [comment]
![uponlogin](https://cloud.githubusercontent.com/assets/24968607/23589745/fabb224a-01ca-11e7-8d2a-24a5e887d1c2.PNG)

Crash upon login, I think it's broke the world.

**Comment by Techatar** [comment]
[crash-2017-03-05_18.22.27-server.txt](https://github.com/AllTheMods/ATM-Illumination/files/819597/crash-2017-03-05_18.22.27-server.txt)

Brand new world. One of the first quests requires bones so I cannot avoid skeletons. Same crash, same issue, the same world breaking bug. :(

**Comment by DJ-Whisper** [comment]
If you take a look at the issue I opened up previously about the ticking arrow, you'll note that I had the same issue. The author provides a temporary fix by removing The Levels mod. Hope this helps you get into the game and playing.

**Comment by al132** [comment]
I have released version 0.6.5 and I decided to just remove levels, so this problem will be fixed now

**Comment by Techatar** [comment]
Will you be adding anything similar in the future?
I find that mod really cool and it adds something fun.

**Comment by al132** [comment]
Do you have any suggestions?

**Comment by Techatar** [comment]
Weapon XP
Inspired by TheXFactor117's Levels mod, Weapon XP is a work-in-progress mod that allows you to level up your weapons by earning experience.

**Comment by al132** [comment]
I have just opened a new issue for mod suggestions. https://github.com/AllTheMods/ATM-Illumination/issues/12 you can suggest that and anything else that comes to mind
