### ISSUE TITLE
Metal Ingots Issue

### ISSUE THREAD

**Issue by Rasip** [AllTheMods/ATM-Illumination#13]
Every way i can find to make ingots is either gated behind the nether (Deep Resonance and Aura Cascade) or Tech Reborn's Iron Furnace which requires bricks that can only be made in.. you guessed it, Tech Reborn's Iron Furnace.

The minecraft furnace is disabled. As are Better beginnings smelters and kilns. 

Version 0.6.6

**Comment by al132** [comment]
Deep Resonance isn't gated behind the nether fortunately, it spawns in the overworld as well.

**Comment by Rasip** [comment]
Ah, while the Deep Resonance smelter does require nether bricks the other one does not. 

I'm still wondering how you get an iron furnace that requires bricks that can only be made in an iron furnace. At least according to JEI.
