### ISSUE TITLE
Mobs spawn wearing iron helmets with over 7000 enchants

### ISSUE THREAD

**Issue by chipgeekjr** [AllTheMods/ATM-Illumination#16]
Almost every zombie or skeleton spawns with an enchanted iron helmet that makes it take hardly any damage, which can drop off them when killed. The helmet has over 7000 enchants on it, mostly duplicate level 1 enchants.

**Comment by al132** [comment]
I have heard of this bug before, but I honestly have absolutely no idea what is causing it.

**Comment by al132** [comment]
I think it might have found a solution for the upcoming update (v0.8.2), but i'm not sure yet

**Comment by al132** [comment]
Just released v0.8.2 - this should be fixed now. Please comment if it is still an issue, although note that any mobs that existed during the previous update may still have this issue. Please comment if it's still happening
