### ISSUE TITLE
Quests

### ISSUE THREAD

**Issue by grimcrip** [AllTheMods/ATM-Illumination#17]
I logged in today to play the pack and the quest book is empty, nothing shows. I create another quest book and still nothing also tried using the grave key instead of the physical book and nothing it's just blank. Any help fixing this would be appreciated.

**Comment by rfronz1** [comment]
i am having the exact same issue.  no matter if a reload the game or just start a new world.

**Comment by al132** [comment]
Copy+paste of my response on Reddit to someone who had this issue:

> This is primarily the fault of my addon BQ: Auto Reload, which has caused this issue on rare occasions. I have decided to re-write the entire questbook in HQM now that it has been fixed up a bit in the last month or two. I should have an update out by Monday at the latest. For now almost all of the quests will be detection tasks rather than crafting tasks, so you'll be able to breeze back through to where you are now pretty quickly.

**Comment by al132** [comment]
The pack has updated with HQM today, closing this issue.
