### ISSUE TITLE
Uncraftable items required in many recipes.

### ISSUE THREAD

**Issue by donoya** [AllTheMods/ATM-Illumination#18]
There is an instance in voidcraft, for example, where it requires the vanilla furnace to make the void macerator, which is required for much of the items in that mod. But just enabling the furnace recipe isn't enough as the ores from harder ores seem to replace the vanilla ores, which are only replaceable with the packaged ores which I don't know how to obtain. Also, the iron furnace needs sandy bricks, which requires bricks, which requires the use of a furnace. and since the only other furnace recipe requires the iron furnace, I couldn't find out how to smelt things. This blocks off much of the progression.

**Comment by neoc666** [comment]
There is a cascading furnace which is part of a quest.

**Comment by donoya** [comment]
Good to know. The voidcraft recipes still need addressing, but thanks anyways.

**Comment by al132** [comment]
In the update I just released (v0.8.2) I added a tooltip to the furnace mentioning that the cascading smelter is required instead, hopefully this clears up some ambiguity. I also added an alternate recipe for the void macerator.
