### ISSUE TITLE
0.8.1 on Curse/Twich launcher - error downloading JEI mod

### ISSUE THREAD

**Issue by CDArena** [AllTheMods/ATM-Illumination#21]
Upgrading to 0.8.1 fails - cannot download http://addons.cursecdn.com/files/2403/107/jei_1.10.2-3.14.7.417.jar

(I also tried doing it by googling and downloading manually - this also failed with error 524 - Timeout)

I know that JEI isn't your mod, so you might want to roll back/forward a version to keep your mod pack installable.

**Comment by al132** [comment]
Strange. Anyway, I just released Illumination v0.8.2 which should have fixed this issue.
