### ISSUE TITLE
Typo in Questbook

### ISSUE THREAD

**Issue by Towsty** [AllTheMods/ATM-Illumination#4]
Pack version 0.61

Astral Sorcery Journal Quest

![image](https://cloud.githubusercontent.com/assets/5897643/23106959/d8b472ca-f6ba-11e6-9c30-a702420bd189.png)

Pretty sure you meant "The aquamarine can be found..."

**Comment by al132** [comment]
Good call, thanks.

**Comment by al132** [comment]
Fixed for 0.6.3
