### ISSUE TITLE
Arrow ticking entity

### ISSUE THREAD

**Issue by DJ-Whisper** [AllTheMods/ATM-Illumination#9]
I had noticed that someone else had a problem with a vanilla aspect of minecraft ticking (polar bear). I've got somewhat the same problem but  with skeletons shooting me with arrows. If I'm not looking at them they can hit me, but if I face them the arrow seems to rebound off and then crashes with the arrow backwards for half a second before the screen crashes to desktop.

This is the second world it's happened in, and each time it's after the first night after having dug in so it's fairly quick in the game.

What follows are the three crash reports I've gotten, the last one is after the latest update (0.6.4)

[crash-2017-03-01_01.49.53-server.txt](https://github.com/AllTheMods/ATM-Illumination/files/819125/crash-2017-03-01_01.49.53-server.txt)
[crash-2017-03-01_01.56.41-server.txt](https://github.com/AllTheMods/ATM-Illumination/files/819126/crash-2017-03-01_01.56.41-server.txt)
[crash-2017-03-04_22.28.13-server.txt](https://github.com/AllTheMods/ATM-Illumination/files/819127/crash-2017-03-04_22.28.13-server.txt)

**Comment by al132** [comment]
A few other people have had this bug as well. It's caused by the mod Levels. Until I figure out what to do for the next release you can just take the mod out in the mean time, as it's completely non-essential.

**Comment by al132** [comment]
Levels has been removed in the most recent release
